name: 'train_novel_view'

stage1_ckpt: 'experiments/pretrain_0402/ckpt/pretrain_final.pth'
lr: 0.0005
wdecay: 1e-5
batch_size: 1
num_steps: 100000
restore_ckpt: 'novel_view/unimatch_gps/experiment/train_EVAGaussian_0403/ckpt/train_EVAGaussian_final.pth'

dataset:
  anchor: False
  source_id: [0, 1]
  train_novel_id: [2, 3, 4]
  val_novel_id: [3]
  use_hr_img: False
  data_root: 'D:\GitHub\freeviewpoint-camera-control\server\jobs\2025-04-14-16-03-48'
  use_processed_data: False

record:
  loss_freq: 200
  eval_freq: 2000

unimatch:
  unimatch_ckpt: 'unimatch/pretrained/gmstereo-scale2-regrefine3-resumeflowthings-middleburyfthighres-a82bec03.pth'
  inference_size: [512, 768]
  pred_bidir_disp: True
  padding_factor: 32
  upsample_factor: 4
  num_scales: 2
  attn_type: 'self_swin2d_cross_swin1d'
  attn_splits_list: [2, 8]
  corr_radius_list: [-1, 4]
  prop_radius_list: [-1, 1]
  num_reg_refine: 3
  feature_channels: 128
  num_head: 1
  ffn_dim_expansion: 4
  num_transformer_layers: 6
  reg_refine: True
  task: 'stereo'

raft:
  mixed_precision: True
  train_iters: 3
  val_iters: 3
  encoder_dims: [32, 48, 96]
  hidden_dims: [96, 96, 96]

gsnet:
  encoder_dims: [32, 48, 96]
  decoder_dims: [48, 64, 96]
  parm_head_dim: 32